spring:
  kafka:
    consumer:
      group-id: my-group
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    root: INFO              # Set default logging level
#    org.springframework.kafka: DEBUG
    com.jh.kafka: INFO

  # Log file configuration
  file:
    name: ./application.log  # Set the log file path

